openapi: 3.0.0
components:
  schemas:
    preparers:
      type: array
      items:
        type: object
        properties:
          preparerId:
            type: number
          preparerName":
            type: string
  securitySchemes: {}
info:
  title: Get Preparers List API
  description: >-
    This is the API spec for the preparers microservice. Currently this service
    only retrieves all the preparers.
  version: '1'
paths:
  /preparers:
    get:
      operationId: getPreparers
      summary: Get preparers List
      description: Returns all existing preparers from the database
      responses:
        '200':
          description: List of preparers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/preparers'
        '500':
          description: The error trace
          content: {}
